server:
  port: 5000
#  servlet:
#    contextPath: /
spring:
  datasource:
    url: jdbc:h2:mem:leodb
    driverClassName: org.h2.Driver
    username: leo
    password: leo
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    database: h2
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  mvc:
    log-request-details: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
    leo:
      satellite:
        capstoneuiserver: DEBUG
# logging

# External dependency reference paths
matlab-sim:
  host: localhost
  port: 6000
  satTest: ${matlab-sim.host}:${matlab-sim.port}/satTest

